# SPDX-License-Identifier: Apache-2.0

manifest:
  remotes:
    - name: zephyrproject-rtos
      url-base: https://github.com/zephyrproject-rtos
    - name: NordicSemiconductor
      url-base: https://github.com/NordicSemiconductor

  projects:
    - name: zephyr
      remote: zephyrproject-rtos
      revision: v3.6-branch
      import:
        name-allowlist:
          - edtt
    # Use Nordic repo to pull in https://github.com/NordicSemiconductor/zcbor/pull/407
    - name: zcbor
      remote: NordicSemiconductor
      revision: 16648fb060d857f164635ca4e8eaa716d906d244
      path: modules/lib/zcbor
